#
# File: Makefile
# Creator: George Ferguson
# Created: Wed Jun 20 15:12:58 2012
# Time-stamp: <Wed Oct 14 16:17:31 CDT 2015 lgalescu>
#

NAME = trips-cabot

include ../Makefile-common

install:: BlockNames.tsv
	$(INSTALL_DATA) $^ $(etcdir)
