#
# File: src/LanguageLearner/Makefile
# Creator: George Ferguson
# Created: Fri Aug 24 10:42:52 2012
# Time-stamp: <Fri Aug 24 10:43:27 EDT 2012 ferguson>
#

NAME = LanguageLearner
DEFSYS = defsys.lisp
SYSTEM = :llearner

CONFIGDIR=../config
include $(CONFIGDIR)/lisp/prog.mk
